We are going to cover indroduction to tensors and manipulate tensors and tensors and numpy

In [ ]:
# import tensorflow#
import tensorflow as tf
print(tf.__version__)

2.13.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(6)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
# Check the numer of dimensions
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant ([3,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a metrics
metrics = tf.constant([[10,8],[4,5]])
metrics.ndim

2

In [ ]:
another_metrix = tf.constant([[[10.4,7.5],[45.3,5.6]]],dtype =tf.float64)
another_metrix.ndim

3

In [ ]:
#  Now using tf.varaible cretaing tensors
varaible = tf.Variable([6,5])
constant =tf.constant ([6,4])
varaible,constant
varaible[0].assign(4)
# constant[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [ ]:
# Creating rnadom tensors two random tensors but same tensors
random_1 =tf.random.Generator.from_seed(32)
random_1 = random_1.normal(shape=[2,2])

random_2 =tf.random.Generator.from_seed(32)
random_2 =random_2.normal(shape=[2,2])
random_1 == random_2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[10,7],[3,4]])
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled,seed = 42 ) #operational level

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
#other ways to create tensors
tf.ones([10,7]) #tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Numpy array into tensors (they are all similar ,but tensors can work on GPU which is much faster)
import numpy as np
numpy_1 = np.arange(1,25)
tensor_1 = tf.constant(numpy_1,shape=(3,2,4)) # its becomes a tensor here
tensor_1

<tf.Tensor: shape=(3, 2, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])>

tensfor attirbutes
Shape tensor.shape
Rank tensor.ndim
Axis or dimension tansor[0]
Size tf.size

In [ ]:
# create a rank 4 tensor
rank_4 =tf.zeros(shape =[2,2,2,2])
rank_4.ndim

4

In [ ]:
tf.size(rank_4) #16 (2*2*2*2)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [ ]:
rank_4.dtype

tf.float32

In [ ]:
# INDEXING IN TENSOR
rank_4[:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get the first element from each dimension
rank_4[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[0., 0.]]]], dtype=float32)>

In [ ]:
#creat a rank 2
rank_2 = tf.constant([[10,7],[3,4]])
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#Add in extra dimension
ran_3 = rank_2 [...,tf.newaxis] # altrantive tf.newaxis is tf.expand_dims(rank_3, axis = -1)
ran_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
rank_3= tf.expand_dims(ran_3, axis = 0)
rank_3

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[10],
         [ 7]],

        [[ 3],
         [ 4]]]], dtype=int32)>

Manipulation Tensors

In [ ]:
#Basic operations
tensor =tf.constant([[10,7],[3,4]])
tensor+10
tensor - 10 #tf.add(tensor,10)
tensor * 10 #tf.mutiply() -- this will be sped up in GPU
tensor /10
tensor // 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 0]], dtype=int32)>

Matrix mutiplication

In [ ]:
# Matrix multiplcation
tf.matmul(tensor,tensor) #tf.linalg.matmul


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor_1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor_2 = tf.constant([[3,5],[6,7],[1,8]])
tf.matmul(tensor_1,tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
tensor @ tensor #pythom matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
'tf.reshape(input ,shape=(what ever shape you give))'

The dot product

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.tensordot(tensor,tensor,axes =1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

Changing the datatype of tensor

In [ ]:
tensor_1 = tf.constant([1,2])
tensor_1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
# change 32 bot precision to change 16 bit precision ,the default is 32 bit precision, and 16 bit for mordern operators runs faster in 16 bit
tensor_1 = tf.cast(tensor_1 ,dtype =tf.int16)
tensor_1

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 2], dtype=int16)>

Aggregating tensors

In [ ]:
j = tf.constant(np.random.randint(0,100, size =50))
j

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([59, 88, 10, 37, 56,  3,  2, 17, 54, 74, 78, 91, 82, 76, 70, 18, 13,
       47, 31, 87, 30, 92, 82, 39, 58, 23, 22, 65,  9, 35, 64, 55, 45, 27,
       22, 43, 70, 79, 45, 35, 52, 27, 67, 11, 56, 17, 77, 31, 66, 88])>

In [ ]:
tf.reduce_min(j)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
tf.reduce_max(j)

<tf.Tensor: shape=(), dtype=int64, numpy=92>

In [ ]:
tf.reduce_mean(j)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
tf.reduce_sum(j)

<tf.Tensor: shape=(), dtype=int64, numpy=2425>

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(j)

<tf.Tensor: shape=(), dtype=int64, numpy=689>

In [ ]:
tf.math.reduce_std(tf.cast(j,tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.261189>

In [ ]:
tf.math.reduce_variance(tf.cast(j,tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=689.65>

In [ ]:
# 'find postional amximum and minimum'
tf.argmax(j)

<tf.Tensor: shape=(), dtype=int64, numpy=21>

In [ ]:
j[tf.argmax(j)]

<tf.Tensor: shape=(), dtype=int64, numpy=92>

In [ ]:
tf.argmin(j)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [ ]:
j[tf.argmin(j)]

<tf.Tensor: shape=(), dtype=int64, numpy=2>

Squeezing a tensor (removing all single dimensions)#

In [ ]:
tf.reshape(j ,shape =(1,1,1,50))

<tf.Tensor: shape=(1, 1, 1, 50), dtype=int64, numpy=
array([[[[59, 88, 10, 37, 56,  3,  2, 17, 54, 74, 78, 91, 82, 76, 70,
          18, 13, 47, 31, 87, 30, 92, 82, 39, 58, 23, 22, 65,  9, 35,
          64, 55, 45, 27, 22, 43, 70, 79, 45, 35, 52, 27, 67, 11, 56,
          17, 77, 31, 66, 88]]]])>

In [ ]:
j_squeez = tf.squeeze(j)
j_squeez

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([59, 88, 10, 37, 56,  3,  2, 17, 54, 74, 78, 91, 82, 76, 70, 18, 13,
       47, 31, 87, 30, 92, 82, 39, 58, 23, 22, 65,  9, 35, 64, 55, 45, 27,
       22, 43, 70, 79, 45, 35, 52, 27, 67, 11, 56, 17, 77, 31, 66, 88])>

In [ ]:
j_squeez.shape

TensorShape([50])

### One hot coding


In [ ]:
list_1 = [1,2,3,4]
tf.one_hot(list_1 ,depth =4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#specify custom value for one hot encoding
tf.one_hot(list_1 ,depth =4,on_value = 'its 4',off_value = 'its not a 4')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'its not a 4', b'its 4', b'its not a 4', b'its not a 4'],
       [b'its not a 4', b'its not a 4', b'its 4', b'its not a 4'],
       [b'its not a 4', b'its not a 4', b'its not a 4', b'its 4'],
       [b'its not a 4', b'its not a 4', b'its not a 4', b'its not a 4']],
      dtype=object)>

Squaring ,log, Square

In [ ]:
h=tf.range(1,20)

In [ ]:
tf.sqrt(tf.cast(h,dtype = tf.float32))

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       , 3.1622777, 3.3166249, 3.4641016,
       3.6055512, 3.7416575, 3.8729835, 4.       , 4.1231055, 4.2426405,
       4.358899 ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(h,dtype = tf.float32))

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
       2.944439 ], dtype=float32)>

###Tensors and numpy

In [ ]:
h =tf.constant(np.arange(1,10))
h

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
np.array(h)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Finding access to GPU


In [ ]:
import tensorflow as tf

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Sep 16 12:01:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------